from django.db import models
from leads.models import Lead, LeadRequest, ACTIVE_STATUS, LEAD_STATUS
from actors.models import Actor
# Create your models here.

class Tempdata(models.Model):
  """
  Store temporary data in the system.
  """ 
  user_id =   models.CharField(max_length=60, null=True, blank=True, help_text="Fixido user ID")
  is_send = models.BooleanField(default=False, help_text="To check if user request seller registration in for the first time.") 
  created = models.DateTimeField(auto_now_add=True, help_text="Auto generated by system.")

  def __unicode__(self):
    return str(self.user_id)
  
  class Meta:
    verbose_name_plural = 'Tempdata'

class ActorBoughtLead(models.Model):
  """
  Stores a reference to all leads bought by a user.
  """
  actor = models.ForeignKey(Actor)
  lead = models.ForeignKey(Lead)  
  # folders = models.ForeignKey('control.Folder', null=True, blank=True, 
  #                             help_text="Folder system to organize the leads. Defined by users. Default is the root folder 'ALL'.")
  status = models.CharField(max_length=10, default='active', choices=LEAD_STATUS, help_text="Lead status, handled by user.")
  note = models.TextField(null=True, blank=True, help_text="Note on the lead created by user.")   
  created = models.DateTimeField(auto_now_add=True, help_text="Auto generated by system.")
  modified = models.DateTimeField(auto_now_add=True, help_text="Auto generated by system.")
  exported = models.DateTimeField(auto_now_add=False, null=True, blank=True, help_text="Date of export.")
  def __unicode__(self):
    return str(self.created)
  

class ActorProvidedLead(models.Model):
  """
  Stores a reference to all lead provided by a user.
  """ 
  actor = models.ForeignKey(Actor)
  lead = models.ForeignKey(Lead)  
  # folders = models.ForeignKey('control.Folder', null=True, blank=True, 
  #                             help_text="Folder system to organize the leads. Defined by users. Default is the root folder 'ALL'.")
  status = models.CharField(max_length=10, default='active', choices=LEAD_STATUS, help_text="Lead status, handle by user.")
  note = models.TextField(null=True, blank=True, help_text="Note on the lead created by user.")   
  created = models.DateTimeField(auto_now_add=True, help_text="Auto generated by system.")
  modified = models.DateTimeField(auto_now_add=True, help_text="Auto generated by system.")
  imported = models.DateTimeField(auto_now_add=False, null=True, blank=True, help_text="Date of import")
  def __unicode__(self):
    return str(self.created)
  
 
class ActorRequestedLead(models.Model):
  """
  Stores a reference to all lead requested by a user.
  """  
  actor = models.ForeignKey(Actor)
  lead_request = models.ForeignKey(LeadRequest)  
  # folders = models.ForeignKey('control.Folder', null=True, blank=True, 
  #                             help_text="Folder system to organize the leads. Defined by users. Default is the root folder 'ALL'.")
  status = models.CharField(max_length=10, default='active', choices=LEAD_STATUS, help_text="Lead status, handle by user.")
  note = models.TextField(null=True, blank=True, help_text="Note on the lead created by user.")   
  created = models.DateTimeField(auto_now_add=True, help_text="Auto generated by system.")
  modified = models.DateTimeField(auto_now_add=True, help_text="Auto generated by system.")
  def __unicode__(self):
    return str(self.created)

