# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tempdata',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('user_id', models.CharField(help_text=b'Fixido user ID', max_length=60, null=True, blank=True)),
                ('is_send', models.BooleanField(default=False, help_text=b'To check if user request seller registration in for the first time.')),
                ('created', models.DateTimeField(help_text=b'Auto generated by system.', auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Tempdata',
            },
        ),
    ]
