# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '__first__'),
        ('leads', '__first__'),
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActorBoughtLead',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('status', models.CharField(default=b'active', help_text=b'Lead status, handled by user.', max_length=10, choices=[(b'active', 'Active'), (b'inactive', 'Inactive'), (b'test', 'Test')])),
                ('note', models.TextField(help_text=b'Note on the lead created by user.', null=True, blank=True)),
                ('created', models.DateTimeField(help_text=b'Auto generated by system.', auto_now_add=True)),
                ('modified', models.DateTimeField(help_text=b'Auto generated by system.', auto_now_add=True)),
                ('exported', models.DateTimeField(help_text=b'Date of export.', null=True, blank=True)),
                ('actor', models.ForeignKey(to='actors.Actor')),
                ('lead', models.ForeignKey(to='leads.Lead')),
            ],
        ),
        migrations.CreateModel(
            name='ActorProvidedLead',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('status', models.CharField(default=b'active', help_text=b'Lead status, handle by user.', max_length=10, choices=[(b'active', 'Active'), (b'inactive', 'Inactive'), (b'test', 'Test')])),
                ('note', models.TextField(help_text=b'Note on the lead created by user.', null=True, blank=True)),
                ('created', models.DateTimeField(help_text=b'Auto generated by system.', auto_now_add=True)),
                ('modified', models.DateTimeField(help_text=b'Auto generated by system.', auto_now_add=True)),
                ('imported', models.DateTimeField(help_text=b'Date of import', null=True, blank=True)),
                ('actor', models.ForeignKey(to='actors.Actor')),
                ('lead', models.ForeignKey(to='leads.Lead')),
            ],
        ),
        migrations.CreateModel(
            name='ActorRequestedLead',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('status', models.CharField(default=b'active', help_text=b'Lead status, handle by user.', max_length=10, choices=[(b'active', 'Active'), (b'inactive', 'Inactive'), (b'test', 'Test')])),
                ('note', models.TextField(help_text=b'Note on the lead created by user.', null=True, blank=True)),
                ('created', models.DateTimeField(help_text=b'Auto generated by system.', auto_now_add=True)),
                ('modified', models.DateTimeField(help_text=b'Auto generated by system.', auto_now_add=True)),
                ('actor', models.ForeignKey(to='actors.Actor')),
                ('lead_request', models.ForeignKey(to='leads.LeadRequest')),
            ],
        ),
    ]
